services:
  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:5001

  backend:
    build: ./backend
    ports:
      - "5001:5001"
    networks:
      - app-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - api_key

  prometheus:
    image: prom/prometheus:v2.45.0
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    networks:
      - app-network

  grafana:
    image: grafana/grafana:9.5.2
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}

networks:
  app-network:
    driver: bridge

secrets:
  api_key:
    file: ./api_key.txt